chore: suppress shiki error
```
Twoslash verification failed

----------
Error in docs/1.getting-started/11.testing.md:582
ShikiError: Language `html` not found, you may need to load it first
----------
```